### ISSUE TITLE
Not well optimised for Android browsers.

### ISSUE THREAD

**Issue by monkey-0028** [Ankush263/MarketX#1]
![Screenshot_20240117-153022.png](https://github.com/Ankush263/MarketX/assets/126169828/305d02de-34d8-4e29-9123-7639f00a871c)

In this photo.. most part of the  video is not visible.

![Screenshot_20240117-153131.png](https://github.com/Ankush263/MarketX/assets/126169828/915a2bfc-2e10-45d6-985f-e54d95364ccf)

Here the txt written in smaller font is not visible.

Maybe the issue is related to resolution and different screen sizes.

**Comment by Ankush263** [comment]
This project is not for small screens, only for desktop users
